### ISSUE TITLE
Not compiled on Arduino UNO

### ISSUE THREAD

**Issue by mahmoud-samy** [mysensors/Arduino#144]
Just pulled the master branch to migrate from 1.4 to 1.5. but it's not compiling
Error: 
C:\Users\msamy\Documents\Arduino\libraries\MySensors\MyHwATMega328.cpp: In function 'void powerDown(period_t)':
C:\Users\msamy\Documents\Arduino\libraries\MySensors\MyHwATMega328.cpp:99: error: 'sleep_bod_disable' was not declared in this scope

**Comment by henrikekblad** [comment]
Running the latest Arduino IDE?

**Comment by mahmoud-samy** [comment]
1.0.5-r2

**Comment by tbowmo** [comment]
Try upgrading to 1.6.x (latest official release)  That would probably solve
the issue

**Comment by mahmoud-samy** [comment]
It works with 1.6.3.

Thanks
